[package]
name = "amaze"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
heapless = "0.7"
modular-bitfield = "0.11"

[features]
default = ["maze_32x32"]
maze_8x8 = []
maze_16x16 = []
maze_32x32 = []

[[example]]
name = "example"
